services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always

    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banking.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

volumes:
  postgres_data: